def input_number():
    num = input("Введите цифру: ")
    print(num)

input_number()
input_number()
input_number()
input_number()
input_number()
input_number()
input_number()
input_number()
input_number()
input_number()
input_number()
